<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-OHBQ9CF" failures="2" tests="5" name="Test" time="27.544" errors="0" timestamp="2023-03-29T21:31:07 IST">
  <testcase classname="Test.scenario_01_Test" name="validate_Simple_Form_Demo_URL" time="1.151">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Test.scenario_01_Test.validate_Simple_Form_Demo_URL(scenario_01_Test.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- validate_Simple_Form_Demo_URL -->
  <testcase classname="Test.scenario_01_Test" name="validate_Entered_Message" time="3.801"/>
  <testcase classname="Test.scenario_03_Test" name="validate_Error_Message" time="0.931"/>
  <testcase classname="Test.scenario_03_Test" name="validate_Success_Message" time="5.545"/>
  <testcase classname="Test.scenario_02_Test" name="validate_Dragged_Value" time="1.151">
    <failure type="java.lang.AssertionError" message="expected [95] but found [89]">
      <![CDATA[java.lang.AssertionError: expected [95] but found [89]
at Test.scenario_02_Test.validate_Dragged_Value(scenario_02_Test.java:23)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- validate_Dragged_Value -->
</testsuite> <!-- Test -->
